default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Tiw@rikush13 
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ror_task_event_management_development

test:
  <<: *default
  database: ror_task_event_management_test

production:
  <<: *default
  database: ror_task_event_management_production
  username: ror_task_event_management
  password: <%= ENV['ROR_TASK_EVENT_MANAGEMENT_DATABASE_PASSWORD'] %>
